/**
 * Handicap type
 */
export enum HandicapType{
    BLINDNESS= "BLINDNESS",
    LOW_VISION= "LOW_VISION",
    HEARING_IMPAIRMENT= "HEARING_IMPAIRMENT",
    SPEECH_AND_LANGUAGE_DISABILITY= "SPEECH_AND_LANGUAGE_DISABILITY",
    LOCOMOTOR_DISABILITY= "LOCOMOTOR_DISABILITY",
    MENTAL_ILLNESS= "MENTAL_ILLNESS",
    LEARNING_DISABILITY= "LEARNING_DISABILITY",
    CEREBRAL_PALSY= "CEREBRAL_PALSY",
    AUTISM= "AUTISM",
    MULTIPLE_DISABILITY= "MULTIPLE_DISABILITY",
    LEPROSY_CURED_PERSONS= "LEPROSY_CURED_PERSONS",
    DWARFISM= "DWARFISM",
    INTELLECTUAL_DISABILITY= "INTELLECTUAL_DISABILITY",
    MUSCULAR_DISABILITY= "MUSCULAR_DISABILITY",
    CHORIONIC_NEUROLOGICAL_CONDITIONS= "CHORIONIC_NEUROLOGICAL_CONDITIONS",
    MULTIPLE_SCLEROSIS= "MULTIPLE_SCLEROSIS",
    THALASSEMIA= "THALASSEMIA",
    HEMOPHILIA= "HEMOPHILIA",
    SICKLE_CELL_DISEASE= "SICKLE_CELL_DISEASE",
    ACID_ATTACK_VICTIM= "ACID_ATTACK_VICTIM",
    PARKINSONS_DISEASE = "PARKINSONS_DISEASE"
}